config/routes.rb
Rails.application.routes.draw do
  #get 'books/index'
  #get 'books/show'
  #get 'books/new'
  #get 'books/edit'
  #get 'books/delete'
  
  resources :books do
  
    member do
      get :delete
    end
  
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new({:title => 'Default'})
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to(books_path)
    else
      render('new')
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update_attributes(book_params)
      redirect_to(books_path(@book))
    else
      render('edit')
    end
  end


  def edit
    @book = Book.find(params[:id])
  end

  def delete
    @book = Book.find(params[:id])
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to(books_path)
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :price, :published_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/delete.html.erb
<% @page_title = "Delete Book" %>

<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this Book?</p>

    <p class="reference-name"><%= f.object.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="book edit">
  <h2>Update Book</h2>

  <%= form_for(@book) do |f| %>

    <table summary="Book form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.text_field(:genre) %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
      <tr>
        <th>Published Date</th>
        <td><%= f.text_field(:published_date) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Book") %>
    </div>

  <% end %>
</div>

app/views/books/index.html.erb
<div class="books index"> 
    <h2> Books </h2>

    <%= link_to("Add new Book", new_book_path , :class=> 'action new') %>
    <table class="listing" summary="Book list">
        <tr class="header">
            <th> # </th>
            <th> Title </th>
            <th> Author </th>
            <th> Genre </th>
            <th> Price </th>
            <th> published-date </th>
        </tr>
        <% @books.each do |book| %>
        <tr>
            <td> <%= book.id %> </td>
            <td> <%= book.title %> </td>
            <td class="center"> <%= book.author %> </td>
            <td class="center"> <%= book.genre %> </td>
            <td class="center"> <%= book.price %> </td>
            <td class="center"> <%= book.published_date %> </td>
            <td class="actions">
                <%= link_to("Show", book_path(book), :class => 'action show') %>
                <%= link_to("Edit", edit_book_path(book), :class => 'action edit') %>
                <%= link_to("Delete", delete_book_path(book), :class => 'action delete') %>
            </td>
        </tr>
        <% end %>
    </table>

</div>

app/views/books/new.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="book new">
  <h2>Create Book</h2>

  <%= form_for(@book) do |f| %>

    <table summary="Book form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.text_field(:genre) %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
      <tr>
        <th>Published Date</th>
        <td><%= f.text_field(:published_date) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Book") %>
    </div>

  <% end %>
</div>

app/views/books/show.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="Books show">
  <h2>Show Book</h2>

  <table summary="Book detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= @book.genre %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <th>Published Date</th>
      <td><%= @book.published_date %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @book.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @book.updated_at %></td>
    </tr>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookProj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>